service: expenses

plugins:
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  environment:
    PG_URL: ${self:custom.environment.pgUrl}
    NODE_ENV: ${self:custom.environment.nodeEnv}
    S3_ENDPOINT: ${self:custom.environment.s3Endpoint}
functions:
  parse:
    handler: handler.parse
events:
  # - s3: expenseskon --> this works but does not create the event
  - s3:
    bucket: expensescon
    event: s3:ObjectCreated:*

custom:
  stage: ${opt:stage, 'local'}
  environment: ${file(../env.yml):${self:custom.stage}, file(../env.yml):default}

  localstack:
    host: http://localhost
    stages:
      - local
    endpoints:
      S3: http://localhost:4568
      Lambda: http://localhost:4567
    lambda:
      # Enable this flag to improve performance
      mountCode: True
